// <auto-generated />
using System;
using BinaryPrediction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinaryPrediction.Infrastructure.Migrations
{
    [DbContext(typeof(BinaryPredictionDbContext))]
    [Migration("20260612055711_AddPredictionResolutionHistoryTableV2")]
    partial class AddPredictionResolutionHistoryTableV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinaryPrediction.Core.Entities.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("Edge")
                        .HasColumnType("numeric")
                        .HasColumnName("edge");

                    b.Property<decimal>("EstimatedProbability")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("estimated_probability");

                    b.Property<string>("KeyReasonsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_reasons_json");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("MarketProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("market_probability");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RiskFactorsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_factors_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_analyses_market_id_created_at_utc");

                    b.ToTable("ai_analyses", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost_usd");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_type");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id")
                        .HasName("pk_ai_usage_records");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usage_records_created_at_utc");

                    b.HasIndex("Model")
                        .HasDatabaseName("ix_ai_usage_records_model");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("ix_ai_usage_records_operation_type");

                    b.ToTable("ai_usage_records", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_alerts_market_id_created_at_utc");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.CalibrationTrendSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualAccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_accuracy_percentage");

                    b.Property<decimal>("CalibrationError")
                        .HasColumnType("numeric")
                        .HasColumnName("calibration_error");

                    b.Property<string>("ConfidenceRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence_range");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("ExpectedAccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_accuracy_percentage");

                    b.Property<int>("PredictionCount")
                        .HasColumnType("integer")
                        .HasColumnName("prediction_count");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date_utc");

                    b.HasKey("Id")
                        .HasName("pk_calibration_trend_snapshots");

                    b.HasIndex("ConfidenceRange", "SnapshotDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_calibration_trend_snapshots_confidence_range_snapshot_date_");

                    b.ToTable("calibration_trend_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.CategoryPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("accuracy_percentage");

                    b.Property<decimal>("AverageBrierScore")
                        .HasColumnType("numeric")
                        .HasColumnName("average_brier_score");

                    b.Property<int>("CorrectPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("correct_predictions");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PredictionCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_category_id");

                    b.Property<int>("PredictionCount")
                        .HasColumnType("integer")
                        .HasColumnName("prediction_count");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date_utc");

                    b.HasKey("Id")
                        .HasName("pk_category_performance_snapshots");

                    b.HasIndex("PredictionCategoryId", "SnapshotDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_category_performance_snapshots_prediction_category_id_snaps");

                    b.ToTable("category_performance_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.EligibleMarketView", b =>
                {
                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("EstimatedResolutionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_resolution_date_utc");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Liquidity")
                        .HasColumnType("numeric")
                        .HasColumnName("liquidity");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric")
                        .HasColumnName("probability");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.ToTable((string)null);

                    b.ToView("eligible_markets_view", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ActualOutcome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actual_outcome");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("EligibleForAnalysis")
                        .HasColumnType("boolean")
                        .HasColumnName("eligible_for_analysis");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("EstimatedResolutionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_resolution_date_utc");

                    b.Property<DateTimeOffset?>("LastQualityEvaluationUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_quality_evaluation_utc");

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liquidity");

                    b.Property<Guid?>("PredictionCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_category_id");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric")
                        .HasColumnName("probability");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.HasIndex("PredictionCategoryId")
                        .HasDatabaseName("ix_markets_prediction_category_id");

                    b.HasIndex("ResolvedAtUtc")
                        .HasDatabaseName("ix_markets_resolved_at_utc");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_markets_slug");

                    b.HasIndex("Active", "Closed")
                        .HasDatabaseName("ix_markets_active_closed");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketAnalysisQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_market_analysis_queue");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_market_analysis_queue_created_at_utc");

                    b.HasIndex("MarketId")
                        .IsUnique()
                        .HasDatabaseName("ux_market_analysis_queue_active")
                        .HasFilter("status IN ('Pending', 'Processing')");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_market_analysis_queue_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_market_analysis_queue_status");

                    b.ToTable("market_analysis_queue", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liquidity");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("Probability")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("probability");

                    b.HasKey("Id")
                        .HasName("pk_market_snapshots");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_market_snapshots_market_id_created_at_utc");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.OpportunityAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageGapPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("average_gap_percentage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("LargestGapPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("largest_gap_percentage");

                    b.Property<int>("OpportunityCount")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_count");

                    b.Property<DateOnly>("SnapshotDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date_utc");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_analytics_snapshots");

                    b.HasIndex("SnapshotDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunity_analytics_snapshots_snapshot_date_utc");

                    b.ToTable("opportunity_analytics_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.OpportunityLifecycleSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_count");

                    b.Property<int>("ExpiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("expired_count");

                    b.Property<int>("IgnoredCount")
                        .HasColumnType("integer")
                        .HasColumnName("ignored_count");

                    b.Property<int>("OpenCount")
                        .HasColumnType("integer")
                        .HasColumnName("open_count");

                    b.Property<int>("ResolvedCount")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_count");

                    b.Property<DateTimeOffset>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date_utc");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_lifecycle_snapshots");

                    b.ToTable("opportunity_lifecycle_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.OpportunityStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_status_history");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_status_history_opportunity_id");

                    b.ToTable("opportunity_status_history", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutcome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actual_outcome");

                    b.Property<decimal?>("ActualOutcomeProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_outcome_probability");

                    b.Property<decimal>("AiProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("ai_probability");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<decimal?>("BrierScore")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("brier_score");

                    b.Property<decimal>("ConfidencePercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence_percentage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("PredictedOutcome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("predicted_outcome");

                    b.Property<string>("PromptVersionUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version_used");

                    b.Property<string>("ReasoningSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasoning_summary");

                    b.Property<string>("ResolutionSource")
                        .HasColumnType("text")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<bool?>("WasCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("was_correct");

                    b.HasKey("Id")
                        .HasName("pk_predictions");

                    b.HasIndex("AnalysisId")
                        .IsUnique()
                        .HasDatabaseName("ix_predictions_analysis_id");

                    b.HasIndex("ConfidencePercentage")
                        .HasDatabaseName("ix_predictions_confidence_percentage");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_predictions_created_at_utc");

                    b.HasIndex("EvaluatedAtUtc")
                        .HasDatabaseName("ix_predictions_evaluated_at_utc");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_predictions_is_active");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_predictions_market_id");

                    b.HasIndex("WasCorrect")
                        .HasDatabaseName("ix_predictions_was_correct");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionBenchmarkResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccuracyPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("accuracy_percentage");

                    b.Property<decimal>("AverageBrierScore")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("average_brier_score");

                    b.Property<string>("BenchmarkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("benchmark_type");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<int>("CorrectPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("correct_predictions");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("total_predictions");

                    b.HasKey("Id")
                        .HasName("pk_prediction_benchmark_results");

                    b.HasIndex("BenchmarkType")
                        .HasDatabaseName("ix_prediction_benchmark_results_benchmark_type");

                    b.HasIndex("CalculatedAtUtc")
                        .HasDatabaseName("ix_prediction_benchmark_results_calculated_at_utc");

                    b.ToTable("prediction_benchmark_results", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionCalibrationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualAccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_accuracy_percentage");

                    b.Property<decimal>("CalibrationError")
                        .HasColumnType("numeric")
                        .HasColumnName("calibration_error");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<string>("ConfidenceRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence_range");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("ExpectedAccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_accuracy_percentage");

                    b.Property<int>("PredictionCount")
                        .HasColumnType("integer")
                        .HasColumnName("prediction_count");

                    b.HasKey("Id")
                        .HasName("pk_prediction_calibration_snapshots");

                    b.ToTable("prediction_calibration_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_prediction_categories");

                    b.ToTable("prediction_categories", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AiProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("ai_probability");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<decimal>("EdgeThresholdPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("edge_threshold_percentage");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at_utc");

                    b.Property<int>("GapDirection")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("gap_direction");

                    b.Property<bool>("HasEdge")
                        .HasColumnType("boolean")
                        .HasColumnName("has_edge");

                    b.Property<DateTimeOffset?>("IgnoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ignored_at_utc");

                    b.Property<DateTimeOffset>("LastStatusChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_changed_at_utc");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("MarketProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("market_probability");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<decimal>("ProbabilityGap")
                        .HasColumnType("numeric")
                        .HasColumnName("probability_gap");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_prediction_opportunities");

                    b.HasIndex("DetectedAtUtc")
                        .HasDatabaseName("ix_prediction_opportunities_detected_at_utc");

                    b.HasIndex("HasEdge")
                        .HasDatabaseName("ix_prediction_opportunities_has_edge");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_prediction_opportunities_market_id");

                    b.HasIndex("PredictionId")
                        .IsUnique()
                        .HasDatabaseName("ix_prediction_opportunities_prediction_id");

                    b.HasIndex("ProbabilityGap")
                        .HasDatabaseName("ix_prediction_opportunities_probability_gap");

                    b.ToTable("prediction_opportunities", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccuracyPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("accuracy_percentage");

                    b.Property<decimal>("AverageBrierScore")
                        .HasColumnType("numeric")
                        .HasColumnName("average_brier_score");

                    b.Property<int>("CorrectPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("correct_predictions");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date_utc");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("total_predictions");

                    b.HasKey("Id")
                        .HasName("pk_prediction_performance_snapshots");

                    b.HasIndex("SnapshotDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_prediction_performance_snapshots_snapshot_date_utc");

                    b.ToTable("prediction_performance_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionQualitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_percentage");

                    b.Property<double>("AverageBrierScore")
                        .HasColumnType("double precision")
                        .HasColumnName("average_brier_score");

                    b.Property<double>("BenchmarkAdvantage")
                        .HasColumnType("double precision")
                        .HasColumnName("benchmark_advantage");

                    b.Property<double>("CalibrationError")
                        .HasColumnType("double precision")
                        .HasColumnName("calibration_error");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<double>("ImprovementTrend")
                        .HasColumnType("double precision")
                        .HasColumnName("improvement_trend");

                    b.Property<DateTimeOffset>("SnapshotDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date_utc");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("total_predictions");

                    b.HasKey("Id")
                        .HasName("pk_prediction_quality_snapshots");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_prediction_quality_snapshots_created_at_utc");

                    b.HasIndex("SnapshotDateUtc")
                        .HasDatabaseName("ix_prediction_quality_snapshots_snapshot_date_utc");

                    b.ToTable("prediction_quality_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionResolutionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutcome")
                        .HasColumnType("text")
                        .HasColumnName("actual_outcome");

                    b.Property<decimal?>("BrierScore")
                        .HasColumnType("numeric")
                        .HasColumnName("brier_score");

                    b.Property<decimal>("ConfidencePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_percentage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<bool?>("WasCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("was_correct");

                    b.HasKey("Id")
                        .HasName("pk_prediction_resolution_histories");

                    b.ToTable("prediction_resolution_histories", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PromptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_name");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_template");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_prompt_versions");

                    b.HasIndex("PromptName")
                        .HasDatabaseName("ix_prompt_versions_prompt_name");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_versions_version");

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.SystemHealthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("active_markets");

                    b.Property<decimal>("AverageBrierScore")
                        .HasColumnType("numeric")
                        .HasColumnName("average_brier_score");

                    b.Property<int>("CompletedMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("completed_markets");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FailedMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("failed_markets");

                    b.Property<DateTimeOffset?>("LastAnalysisUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analysis_utc");

                    b.Property<DateTimeOffset?>("LastEvaluationUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluation_utc");

                    b.Property<DateTimeOffset?>("LastMarketCollectionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_market_collection_utc");

                    b.Property<DateTimeOffset?>("LastPredictionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_prediction_utc");

                    b.Property<decimal>("PredictionAccuracy")
                        .HasColumnType("numeric")
                        .HasColumnName("prediction_accuracy");

                    b.Property<int>("ProcessingMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("processing_markets");

                    b.Property<int>("QueuedMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("queued_markets");

                    b.Property<int>("ResolvedMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_markets");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalAnalyses")
                        .HasColumnType("integer")
                        .HasColumnName("total_analyses");

                    b.Property<int>("TotalMarkets")
                        .HasColumnType("integer")
                        .HasColumnName("total_markets");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer")
                        .HasColumnName("total_predictions");

                    b.HasKey("Id")
                        .HasName("pk_system_health_snapshots");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_system_health_snapshots_created_at_utc");

                    b.ToTable("system_health_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.WorkerHeartbeat", b =>
                {
                    b.Property<string>("WorkerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_name");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("WorkerName")
                        .HasName("pk_worker_heartbeats");

                    b.ToTable("worker_heartbeats", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.AiAnalysis", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_analyses_markets_market_id");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Alert", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_markets_market_id");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.CategoryPerformanceSnapshot", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.PredictionCategory", "PredictionCategory")
                        .WithMany()
                        .HasForeignKey("PredictionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_performance_snapshots_prediction_categories_predic");

                    b.Navigation("PredictionCategory");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Market", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.PredictionCategory", "PredictionCategory")
                        .WithMany()
                        .HasForeignKey("PredictionCategoryId")
                        .HasConstraintName("fk_markets_prediction_categories_prediction_category_id");

                    b.Navigation("PredictionCategory");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketAnalysisQueueItem", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_analysis_queue_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_snapshots_markets_market_id");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.OpportunityStatusHistory", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.PredictionOpportunity", "Opportunity")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_status_history_prediction_opportunities_opportu");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Prediction", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.AiAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_predictions_ai_analyses_analysis_id");

                    b.HasOne("BinaryPrediction.Core.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_predictions_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionOpportunity", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prediction_opportunities_markets_market_id");

                    b.HasOne("BinaryPrediction.Core.Entities.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prediction_opportunities_predictions_prediction_id");

                    b.Navigation("Market");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.PredictionOpportunity", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
