// <auto-generated />
using System;
using BinaryPrediction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinaryPrediction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BinaryPredictionDbContext))]
    [Migration("20260605070442_UpdateActiveQueueIndex")]
    partial class UpdateActiveQueueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinaryPrediction.Core.Entities.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("Edge")
                        .HasColumnType("numeric")
                        .HasColumnName("edge");

                    b.Property<decimal>("EstimatedProbability")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("estimated_probability");

                    b.Property<string>("KeyReasonsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_reasons_json");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("MarketProbability")
                        .HasColumnType("numeric")
                        .HasColumnName("market_probability");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RiskFactorsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_factors_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_analyses_market_id_created_at_utc");

                    b.ToTable("ai_analyses", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_alerts_market_id_created_at_utc");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.EligibleMarketView", b =>
                {
                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("EstimatedResolutionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_resolution_date_utc");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Liquidity")
                        .HasColumnType("numeric")
                        .HasColumnName("liquidity");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric")
                        .HasColumnName("probability");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.ToTable((string)null);

                    b.ToView("eligible_markets_view", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("EligibleForAnalysis")
                        .HasColumnType("boolean")
                        .HasColumnName("eligible_for_analysis");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("EstimatedResolutionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_resolution_date_utc");

                    b.Property<DateTimeOffset?>("LastQualityEvaluationUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_quality_evaluation_utc");

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liquidity");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric")
                        .HasColumnName("probability");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_markets_slug");

                    b.HasIndex("Active", "Closed")
                        .HasDatabaseName("ix_markets_active_closed");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketAnalysisQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_market_analysis_queue");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_market_analysis_queue_created_at_utc");

                    b.HasIndex("MarketId")
                        .IsUnique()
                        .HasDatabaseName("ux_market_analysis_queue_active")
                        .HasFilter("status IN ('Pending', 'Processing')");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_market_analysis_queue_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_market_analysis_queue_status");

                    b.ToTable("market_analysis_queue", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liquidity");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<decimal>("Probability")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("probability");

                    b.HasKey("Id")
                        .HasName("pk_market_snapshots");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_market_snapshots_market_id_created_at_utc");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.AiAnalysis", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_analyses_markets_market_id");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.Alert", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_markets_market_id");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketAnalysisQueueItem", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_analysis_queue_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("BinaryPrediction.Core.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("BinaryPrediction.Core.Entities.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_snapshots_markets_market_id");
                });
#pragma warning restore 612, 618
        }
    }
}
